name: Lint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install poetry
      - run: which poetry
      - run: poetry install
      - name: Black
        run: poetry run black --check src/ tests/
      - name: Isort
        run: poetry run isort --check-only src/ tests/
#      - name: Flake8
#        run: poetry run flake8 src/ tests/ --exclude __init__.py
