name: test

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - '**.py'
      - 'pyproject.toml'

jobs:
  test:
    strategy:
      matrix:
        version: ['3.13']
        os: ['ubuntu-latest', 'windows-latest']
    name: Python ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest --verbose
